
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-23T14:03:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "966ac59da243052248d7ce06305a35d0d354c3ae",
 "version": "0.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
